library(readr)
library(dplyr)
library(ggplot2)


input_csv <- "topological_correlations.csv"
plot_output <- "mu_disassortative_trend_mle.png"

# Load the data generated by your previous script
df <- read_csv(input_csv, show_col_types = FALSE)


# Convert the YYYY_MM string to a continuous Date object
df <- df %>%
  mutate(
    date = as.Date(paste0(month, "_01"), format="%Y_%m_%d"),
    year = as.numeric(format(date, "%Y"))
  )

# Flag the 2020-2022 period as "Anomaly" so we can exclude it from the math, 
# but still plot it as ghosted points for visual transparency.
df <- df %>%
  mutate(
    is_anomaly = year %in% c(2020, 2021, 2022),
    # Create a continuous numeric time variable for the regression
    # (Using exact days since the very first snapshot)
    time_numeric = as.numeric(date - min(date))
  )

# Filter out the anomalies to create a pure dataset for the MLE fit
df_clean <- df %>% filter(is_anomaly == FALSE)

# ml fit

mle_model <- lm(mu ~ time_numeric, data = df_clean)

# Extract statistics
model_summary <- summary(mle_model)
slope <- model_summary$coefficients[2, 1]
p_val <- model_summary$coefficients[2, 4]
r_sq  <- model_summary$r.squared

# Extract the exact 95% Confidence Interval for the slope
ci_95 <- confint(mle_model, "time_numeric", level = 0.95)


cat(sprintf("Slope (Trend over time): %.6f\n", slope))
cat(sprintf("95%% Confidence Interval: [%.6f, %.6f]\n", ci_95[1], ci_95[2]))
cat(sprintf("P-value:                 %.2e\n", p_val))



if(slope < 0 && p_val < 0.05) {
  cat("\nCONCLUSION: Statistically significant proof that the network is becoming more disassortative over time.\n\n")
}




p <- ggplot(df, aes(x = date, y = mu)) +
  
  # 1. Plot the Anomaly years as faded grey dots
  geom_point(data = filter(df, is_anomaly == TRUE), 
             color = "grey75", size = 2.5, alpha = 0.6, shape = 4) +
  
  # 2. Plot the valid, clean data as solid blue dots
  geom_point(data = df_clean, color = "#2B83BA", size = 2.5, alpha = 0.9) +
  
  # 3. Draw the MLE Regression line AND the 95% Confidence Interval shaded ribbon
  # We restrict it to 'df_clean' so the line ignores the anomaly years completely
  geom_smooth(data = df_clean, method = "lm", formula = y ~ x, 
              color = "#D7191C", fill = "red", alpha = 0.15, level = 0.95, linewidth = 1.2) +
  
  # Draw a zero-line to distinguish Assortative (Top) from Disassortative (Bottom)
  geom_hline(yintercept = 0, color = "black", linetype = "dashed", linewidth = 1) +
  
  scale_x_date(date_breaks = "2 years", date_labels = "%Y") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5, face = "bold", size = 11),
    axis.title.y = element_text(face = "bold", size = 11),
    panel.grid.minor = element_blank()
  ) +
  labs(
    title = "Longitudinal Evolution of Network Assortativity (\u03bc)",
    subtitle = "Red line represents MLE fit with 95% Confidence Interval ribbon. Grey crosses (2020-2022) excluded from fit.",
    x = "Timeframe",
    y = "Degree Assortativity Exponent (\u03bc)"
  )

# Save the plot
ggsave(plot_output, plot = p, width = 9, height = 6, dpi = 300, bg = "white")
