library(readr)
library(dplyr)
library(stringr)
library(poweRlaw)
library(parallel)

# Directories and files
input_dir <- "degree_distribution"
plot_dir <- "powerlaw_plots"
output_csv <- "powerlaw_results.csv"
stats_file <- "network_monthly_statistics.csv" # To get the exact total nodes

# Number of simulations 
BOOTSTRAP_SIMS <- 100 

if (!dir.exists(plot_dir)) dir.create(plot_dir)

# Load the network statistics to get total nodes for each month
if (!file.exists(stats_file)) {
  stop("Missing network_monthly_statistics.csv file")
}
stats_df <- read_csv(stats_file, show_col_types = FALSE)

# Get the list of degree CSVs
degree_files <- list.files(path = input_dir, pattern = "^degree_dist_.*\\.csv$", full.names = TRUE)

if (length(degree_files) == 0) stop("No degree distribution files found.")

results_list <- list()
cat(sprintf("Starting Power-Law Analysis for %d months \n", length(degree_files)))

# powerlaw fit and bootstrap loop
for (file_path in degree_files) {
  
  filename <- basename(file_path)
  yyyy_mm <- str_extract(filename, "\\d{4}_\\d{2}")
  
  # read data
  deg_df <- read_csv(file_path, show_col_types = FALSE)
  
  # get degrees
  
  # Find the total nodes for this specific month
  month_total_nodes <- stats_df %>% filter(month == yyyy_mm) %>% pull(unique_nodes)
  
  
  # Multiply probability by total nodes to get exact counts, then reconstruct the vector
  counts <- round(deg_df$probability * month_total_nodes)
  raw_degrees <- rep(deg_df$degree, counts)
  
  # Filter out 0 degrees
  valid_degrees <- raw_degrees[raw_degrees > 0]
  
  
  # fit powerlaw
  m_pl <- displ$new(valid_degrees)
  est <- estimate_xmin(m_pl)
  m_pl$setXmin(est)
  
  # compute bootstrap simulations
  bs <- bootstrap(m_pl, no_of_sims = BOOTSTRAP_SIMS, threads = detectCores() - 1)
  
  # Extract 95% Confidence Intervals
  ci_xmin <- quantile(bs$bootstraps$xmin, probs = c(0.025, 0.975), na.rm = TRUE)
  ci_alpha <- quantile(bs$bootstraps$pars, probs = c(0.025, 0.975), na.rm = TRUE)
  
  # Save plot
  plot_filepath <- file.path(plot_dir, paste0("powerlaw_fit_", yyyy_mm, ".png"))
  png(plot_filepath, width = 800, height = 600, res = 100)
  
  plot(m_pl, col = "black", bg = "grey80", pch = 21,
       main = paste("Power-Law Fit: BGP Network", yyyy_mm),
       xlab = "Degree (k)", ylab = "CDF P(X >= k)")
  lines(m_pl, col = "red", lwd = 2)
  
  # Add a legend with the calculated values
  legend("topright", 
         legend = c(sprintf("x_min = %d", m_pl$xmin),
                    sprintf("Alpha = %.3f", m_pl$pars)),
         col = c(NA, "red"), lwd = c(NA, 2), bty = "n")
  
  dev.off() # Close and save the image
  
  # Store results
  results_list[[yyyy_mm]] <- data.frame(
    month = yyyy_mm,
    x_min = m_pl$xmin,
    xmin_ci_lower = ci_xmin[1],
    xmin_ci_upper = ci_xmin[2],
    alpha = m_pl$pars,
    alpha_ci_lower = ci_alpha[1],
    alpha_ci_upper = ci_alpha[2]
  )
  
  cat(sprintf(" Alpha = %.3f [%.3f, %.3f]\n\n", m_pl$pars, ci_alpha[1], ci_alpha[2]))
}

# save csv

final_results_df <- bind_rows(results_list)

# Clean up row names generated by R
rownames(final_results_df) <- NULL 

write_csv(final_results_df, output_csv)
